included:
  - tama
  - BusWidget
  - TimetableWidget
  - PrintShareExtension

excluded:
  - Pods
  - Carthage
  - build
  - DerivedData
  - "*.playground"
  - "*/Resources/*"
  - "*/Legacy/*"
  - "*/Generated/*"
  - "*/Preview Content/*"

disabled_rules:
  - todo
  - trailing_whitespace
  - inert_defer

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - privately_owned
  - closure_spacing
  - fatal_error_message
  - first_where
  - number_separator

line_length:
  warning: 140
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 100
  error: 150

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 1500
  error: 2000

force_try:
  severity: warning

force_cast:
  severity: warning

large_tuple:
  warning: 3
  error: 4

identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - x
    - y
    - z
    - i
    - j
    - k
    - db
    - vc
    - ui
    - APP_GROUP_ID
    - to
